fix: add task button styling
Ben0189/Blotz-Task-App pull request #106
Opened 2024-10-08 10:53 UTC by ala233

Fix add task button styling
<img width="1211" alt="Screenshot 2024-10-08 at 9 53 15 PM" src="https://github.com/user-attachments/assets/cae33631-43f0-47a6-80ba-6335c7339d40">

2024-10-08 11:32 UTC, Ben0189 requested changes

2024-10-08 11:32 UTC, Ben0189 commented on blotztask-ui/src/app/task-list/page.tsx
> +    <div className="flex flex-col">
do you need flex here also ? Looks like it is unnecessary?
<div className="flex flex-col">

2024-10-09 07:16 UTC, ala233 commented
latest version of the front-end
<img width="1206" alt="Screenshot 2024-10-09 at 6 12 10 PM" src="https://github.com/user-attachments/assets/e26d9c14-f24a-47ce-b1d0-6f4d45710ea1">

2024-10-10 10:53 UTC, Ben0189 approved these changes

2024-10-10 12:03 UTC, ala233 commented
latest version of the front-end
<img width="1207" alt="Screenshot 2024-10-10 at 11 02 22 PM" src="https://github.com/user-attachments/assets/8e1153bb-bc84-4e97-82e4-ecaa7085111f">

2024-10-10 12:04 UTC, merged