Added fetch task list for All task page and left a setUpdate function…
Ben0189/Blotz-Task-App pull request #113
Opened 2024-10-16 11:40 UTC by PeterOu8

Implemented the fetch list feature. Reused the fetch function to call all created tasks. Data fetched will be stored in a state and updated when the Effect update state changes.

2024-10-16 12:08 UTC, PeterOu8 commented
Changed the exported function to uppercase to avoid error and passed in the update in add-item button to avoid unused function error.

2024-10-16 12:38 UTC, sol-wizard requested changes

2024-10-16 12:38 UTC, sol-wizard commented on blotztask-ui/src/app/task-list/page.tsx
> +    const [update, setUpdate] = useState(false);
i know you trying to update task when the add new task is added, but i will do it in a better way.

i will use a callback function that handle add task instead of using a boolean (this is then more maintainable because next time if you want to do something else after add task you can add in the handle function)

`    const handleAddTask = async () => {
        await loadTasks();
    };`

2024-10-16 12:38 UTC, sol-wizard commented on blotztask-ui/src/app/task-list/page.tsx
> +          <AddTask update={setUpdate}/>
<AddTask update={handleAddTask}/>

2024-10-16 12:38 UTC, sol-wizard commented on blotztask-ui/src/app/task-list/components/add-button.tsx
> +export function AddTask({update}) {
give this param a better name (tips you can use gpt to name it for you)

2024-10-18 14:03 UTC, PeterOu8 commented on blotztask-ui/src/app/task-list/page.tsx
> +    const [update, setUpdate] = useState(false);
Despite of updating task when the new task is added, I also wanted to rerendered the alltask page if any changes are applied. That is my initial thought for update. Do you think using the dependency parameter in useEffect would help or I am getting the whole thing too complicated as add task may just redirect the user to another page?

2024-10-26 09:32 UTC, sol-wizard approved these changes
LGTM 🚀

2024-10-26 13:18 UTC, merged