Day view page fetch task from backend
Ben0189/Blotz-Task-App pull request #121
Opened 2024-11-02 15:32 UTC by PeterOu8

Implemented the fetch task due today feature. Implemented the fetch function to get all tasks due by today's date.

2024-11-04 11:46 UTC, Ben0189 requested changes

2024-11-04 11:46 UTC, Ben0189 commented on blotztask-ui/src/app/task-dayview/page.tsx
> +// import { Checkbox } from '@/components/ui/checkbox';
remove?

2024-11-04 11:46 UTC, Ben0189 commented on blotztask-ui/src/services/taskService.ts
> +      throw new Error('Network response was not ok');
```suggestion
      throw new Error('Error in fetching Task Item from backend');
```

2024-11-04 11:46 UTC, Ben0189 commented on blotztask-ui/tailwind.config.ts
> +        'checkbox': '#989ca4',
what is the checkbox for?

2024-11-04 12:10 UTC, PeterOu8 commented on blotztask-ui/src/app/task-dayview/page.tsx
> +// import { Checkbox } from '@/components/ui/checkbox';
The checkbox will be applied per figma prototype. I tried implement this but realised it was in another ticket.

2024-11-07 10:34 UTC, Ben0189 submitted a review, later dismissed

2024-11-07 10:50 UTC, PeterOu8 commented on blotztask-ui/tailwind.config.ts
> +        'checkbox': '#989ca4',
I have the checkbox component wrote out already but I did not take the ticket. I tried styling the shadcn checkbox component therefore there is another color.

2024-11-08 08:54 UTC, Ben0189 approved these changes

2024-11-08 08:55 UTC, merged