include label in get all task end point
Ben0189/Blotz-Task-App pull request #126
Opened 2024-11-08 10:27 UTC by PeterOu8

Modify get all task endpoint to include label

2024-11-08 10:33 UTC, Ben0189 approved these changes

2024-11-08 10:44 UTC, Ben0189 requested changes

2024-11-08 10:44 UTC, Ben0189 commented on blotztask-api/Models/TaskItemDTO.cs
> +﻿using BlotzTask.Data.Entities;
we should not Using entities in models

The idea is to encap all entity related only at data layer

2024-11-08 10:50 UTC, Ben0189 requested changes

2024-11-08 10:50 UTC, Ben0189 commented on blotztask-api/Models/TaskItemDTO.cs
> +        public Label Label { get; set; }
instead of using label entity, i will create a new DTO class for label

```suggestion
        public Label Label { get; set; }
        public LabelDTO Label { get; set; }

```

2024-11-08 10:50 UTC, Ben0189 commented on blotztask-api/Services/TaskService.cs
> +                    Label = x.Label
over here you will need to map to new dto once you create dto class

Benefit, now you only return necessary data you need to the endpoint, e.g. you dont need label id you just dont need to have it in dto (encapsulation)

2024-11-15 12:34 UTC, PeterOu8 commented on blotztask-api/Models/TaskItemDTO.cs
> +﻿using BlotzTask.Data.Entities;
Got it! the comment crossed out the wrong line I believe but I get what you mean!!

2024-11-15 13:12 UTC, PeterOu8 commented on blotztask-api/Services/TaskService.cs
> +                    Label = x.Label
Dpne ! the new change applied: encapsulate colour and name only.

2024-11-15 13:12 UTC, PeterOu8 commented on blotztask-api/Models/TaskItemDTO.cs
> +        public Label Label { get; set; }
Done

2024-11-16 01:02 UTC, Ben0189 approved these changes

2024-11-16 01:19 UTC, merged