Monthly stats page new function
Ben0189/Blotz-Task-App pull request #127
Opened 2024-11-15 10:16 UTC by JasonRenBang

Implement a monthly stats page.

2024-11-15 10:33 UTC, Ben0189 requested changes

2024-11-15 10:33 UTC, Ben0189 commented on blotztask-ui/package.json
> +  "packageManager": "yarn@1.22.19+sha1.4ba7fc5c6e704fce2066ecbfb0b0d8976fe62447"
why do you change package manager

2024-11-15 10:33 UTC, Ben0189 commented on blotztask-ui/yarn.lock
please remove your yarn lock

2024-11-15 10:33 UTC, Ben0189 commented on blotztask-ui/src/app/monthly-stats/page.tsx
> +import { mock } from 'node:test';
please remove if it is not used

2024-11-15 10:33 UTC, Ben0189 commented on blotztask-ui/src/app/monthly-stats/page.tsx
> +            alt="an incredable image"
try use image attribute

2024-11-15 10:33 UTC, Ben0189 commented on blotztask-ui/src/app/monthly-stats/page.tsx
> +          <p className="font-arial font-bold text-[40px] leading-[100px] tracking-[-0.41px] text-center text-[#278291]">
```suggestion
   text-secondary
```

2024-11-15 10:33 UTC, Ben0189 commented on blotztask-ui/src/app/page.tsx
> +        className="w-[849px] h-[350px] absolute top-[305px] left-[296px]"
dont use absolute

2024-11-15 10:33 UTC, Ben0189 commented on blotztask-ui/src/app/task-dayview/page.tsx
> +  const countTasks = (tasks: taskDto[]): number => {
why do you need to change the day view page

2024-11-17 09:47 UTC, Ben0189 approved these changes

2024-11-17 09:50 UTC, merged

2024-11-17 09:53 UTC, JasonRenBang commented
all good