Seed default label data using migration
Ben0189/Blotz-Task-App pull request #128
Opened 2024-11-15 14:56 UTC by PeterOu8

Seeded default labels into table and removed pre-seeded data.

2024-11-16 01:28 UTC, Ben0189 requested changes

2024-11-16 01:28 UTC, Ben0189 commented on blotztask-api/Data/Seeding/BlotzContextSeed.cs
>              await context.SaveChangesAsync();
```suggestion
     Console.WriteLine("No Label found in database. TIPS: "you might need to run database migrations first" ")  
```

2024-11-16 01:28 UTC, Ben0189 commented on blotztask-api/Data/Seeding/BlotzContextSeed.cs
>              Console.WriteLine("Label creation Success.");
```suggestion
```

2024-11-20 10:56 UTC, Ben0189 approved these changes

2024-11-20 10:56 UTC, Ben0189 commented on blotztask-api/Data/Seeding/BlotzContextSeed.cs
>      {
i dont think we need this anymore

2024-11-20 10:56 UTC, Ben0189 commented on blotztask-api/Data/Seeding/BlotzContextSeed.cs
> +        var labelWork = await context.Labels.FirstOrDefaultAsync(l => l.Name == "Work");
We can try to use [Enum](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/enum) instead

2024-11-20 10:56 UTC, Ben0189 commented on blotztask-api/Data/Seeding/BlotzContextSeed.cs
>              Console.WriteLine("Labels are missing. Cannot seed tasks.");
```suggestion
            Console.WriteLine("Label missing. Try to run migrations to seed the label. Failed to seed task");
```

2024-11-22 23:21 UTC, PeterOu8 commented on blotztask-api/Data/Seeding/BlotzContextSeed.cs
> +        var labelWork = await context.Labels.FirstOrDefaultAsync(l => l.Name == "Work");
I feel like enum itself cannot identify a label and in the future there would be some additional customised labels. I am not  sure about how to use this.

2024-11-24 00:07 UTC, Ben0189 requested changes

2024-11-24 00:07 UTC, Ben0189 commented on blotztask-api/Data/Seeding/BlotzContextSeed.cs
> +        var labelWork = await context.Labels.FirstOrDefaultAsync(l => l.Name == "Work");
```suggestion
        var labelWork = await context.Labels.FirstOrDefaultAsync(l => l.Name == LabelType.Work.ToString());
```

2024-11-24 12:27 UTC, sol-wizard approved these changes

2024-11-24 13:24 UTC, merged