I have added the checkbox
Ben0189/Blotz-Task-App pull request #135
Opened 2024-11-22 01:53 UTC by nxn-nicole

I have added the checkbox.
![image](https://github.com/user-attachments/assets/5b0490f1-b844-44cb-89c0-c95aff816f3a)

2024-11-23 01:31 UTC, Ben0189 requested changes

2024-11-23 01:31 UTC, Ben0189 commented on blotztask-ui/src/app/task-list/page.tsx
> +    const [isChecked, setIsChecked] = useState(false);
you probably dont need those in task list page

2024-11-23 01:31 UTC, Ben0189 commented on blotztask-ui/src/app/task-list/page.tsx
> +              }}
you probably dont need the checkbox in task list page

2024-11-29 22:40 UTC, sol-wizard requested changes

2024-11-29 22:40 UTC, sol-wizard commented on blotztask-ui/src/app/task-dayview/page.tsx
> +export const completeTaskForToday = async (taskId : number): Promise<string> => {
we can abstract this method to the service layer

2024-12-05 03:52 UTC, nxn-nicole commented on blotztask-ui/src/app/task-dayview/page.tsx
> +export const completeTaskForToday = async (taskId : number): Promise<string> => {
I have moved it to service layer.

2024-12-05 12:30 UTC, Ben0189 submitted a review, later dismissed
LGTM

2024-12-07 23:03 UTC, Ben0189 requested changes

2024-12-07 23:03 UTC, Ben0189 commented on blotztask-ui/src/app/task-dayview/page.tsx
> +      setIncompleteTasks(prevTasks => prevTasks.filter(task => task.id !== taskId));
dont just do filter in frontend, i will do another call to backend to load the data again, imagine if your backend complete task endpoint when wrong, your are still filtering the data in frontend, this is misleading information

2024-12-07 23:03 UTC, Ben0189 commented on blotztask-ui/src/app/task-dayview/page.tsx
> +      setIncompleteTasks(prevTasks => prevTasks.filter(task => task.id !== taskId));
```suggestion
loadIncompleteTasks() 
```

2024-12-08 13:14 UTC, nxn-nicole commented on blotztask-ui/src/app/task-dayview/page.tsx
> +      setIncompleteTasks(prevTasks => prevTasks.filter(task => task.id !== taskId));
I have changed this

2024-12-09 02:36 UTC, PeterOu8 requested changes

2024-12-09 02:36 UTC, PeterOu8 commented on blotztask-ui/src/app/task-dayview/page.tsx
> +  const [isChecked, setIsChecked] = useState<boolean>(false);
Remove this line. This is buggy since you are assigning one state to multiple checkboxes which will cause all the checkboxes to be ticked when only one box is selected.

2024-12-09 02:36 UTC, PeterOu8 commented on blotztask-ui/src/app/task-dayview/page.tsx
> +      loadIncompleteTasks();
Ideally, you do not want to call the fetch API over and over because it will affect performance. It is in a useEffect hook (Means this will only be called once on first time page render).

2024-12-09 02:36 UTC, PeterOu8 commented on blotztask-ui/src/app/task-dayview/page.tsx
> +    if (checked) {
Do not see this if statement as necessary since the function will only be called when the check state changes.

2024-12-09 02:36 UTC, PeterOu8 commented on blotztask-ui/src/app/task-dayview/page.tsx
> +                          checked={isChecked}
Remove checked unless you have multiple states for each checkbox.

2024-12-09 02:36 UTC, PeterOu8 commented on blotztask-ui/src/app/task-dayview/page.tsx
> +                          onCheckedChange={(checked:boolean) =>
I would personally structure this as  onCheckedChange={() => handleCheckboxChange(task.id) } where hancleCheckBoxChange call the mark as done API and update the tasks from local incompleteTasks state.

2024-12-13 00:34 UTC, nxn-nicole commented on blotztask-ui/src/app/task-dayview/page.tsx
> +import { fetchWithAuth } from '@/utils/fetch-with-auth';
I have removed the unused imports

2024-12-13 00:35 UTC, nxn-nicole commented on blotztask-ui/src/app/task-dayview/page.tsx
> +  const [isChecked, setIsChecked] = useState<boolean>(false);
I have removed this line

2024-12-13 00:46 UTC, nxn-nicole commented on blotztask-ui/src/app/task-dayview/page.tsx
> +    if (checked) {
I have delete this if statement

2024-12-13 00:51 UTC, nxn-nicole commented on blotztask-ui/src/app/task-dayview/page.tsx
> +      loadIncompleteTasks();
I have added the useEffect

2024-12-13 00:51 UTC, nxn-nicole commented on blotztask-ui/src/app/task-dayview/page.tsx
> +                          checked={isChecked}
I have removed checked

2024-12-13 00:51 UTC, nxn-nicole commented on blotztask-ui/src/app/task-dayview/page.tsx
> +                          onCheckedChange={(checked:boolean) =>
I have changed onCheckedChange

2024-12-13 00:54 UTC, nxn-nicole commented on blotztask-ui/src/app/task-list/page.tsx
No I didn't mean to. At first I thought I need to implement the PBI on this page but later I changed it

2024-12-13 07:39 UTC, PeterOu8 requested changes

2024-12-13 07:39 UTC, PeterOu8 commented on blotztask-ui/src/app/task-dayview/page.tsx
> +  const [tasksCompleted, setTasksCompleted] = useState(false);
Unnecessary state.

2024-12-13 07:39 UTC, PeterOu8 commented on blotztask-ui/src/app/task-dayview/page.tsx
> +  const completeTask = async (taskId: number) => {
Redundant function wrapper. Remove this function and just call the function you imported. You are wrapping the service function in another function that does the same thing.

2024-12-13 07:39 UTC, PeterOu8 commented on blotztask-ui/src/app/task-dayview/page.tsx
> +  useEffect(() => {
Redundant Hook. There is a useEffect hook implemented on line 12 and you are using it incorrectly.

2024-12-13 07:39 UTC, PeterOu8 commented on blotztask-ui/src/app/task-dayview/page.tsx
> +    loadIncompleteTasks();
Instead of fetching again. Maybe just do setIncompleteTasks(incompleteTasks.filter((task) => task.id != taskId)) as both would re-render the page and give you what you want - remove the task from the page.

2024-12-14 02:47 UTC, nxn-nicole commented on blotztask-ui/src/app/task-dayview/page.tsx
> +  const [tasksCompleted, setTasksCompleted] = useState(false);
I have deleted this

2024-12-14 02:54 UTC, nxn-nicole reviewed
I have solved all the comments with Ben's help

2024-12-14 02:54 UTC, nxn-nicole commented on blotztask-ui/src/app/task-dayview/page.tsx
> +  useEffect(() => {
I have deleted this

2024-12-14 02:54 UTC, nxn-nicole commented on blotztask-ui/src/app/task-list/page.tsx
Sure I have reverted it

2024-12-16 23:02 UTC, sol-wizard approved these changes

2024-12-18 15:28 UTC, merged