UI changes   add task page
Ben0189/Blotz-Task-App pull request #137
Opened 2024-11-26 09:56 UTC by JasonRenBang

![1732614882690](https://github.com/user-attachments/assets/19146045-348c-4ee1-a919-67aa3c60e94e)
bring all colors back and set work task input area as default

2024-11-26 10:45 UTC, Ben0189 submitted a review, later dismissed

2024-11-26 11:23 UTC, PeterOu8 requested changes
Good work! However, you have the label text colours and the textarea place holder colours are mismatched with the figma prototype. Could you please change those as well?

2024-11-26 11:25 UTC, PeterOu8 commented on blotztask-ui/src/app/add-task/page.tsx
e.g. add the corresponding colour in the tailwind config file and use them in your page. #6021D6 for work label text

2024-11-26 12:55 UTC, JasonRenBang commented on blotztask-ui/src/app/add-task/page.tsx
how about this time

2024-11-26 12:59 UTC, JasonRenBang commented
![1732625932116](https://github.com/user-attachments/assets/9ac4e8b5-40b1-4ae4-955a-c96e8a2eb7ad)

2024-11-26 13:56 UTC, PeterOu8 submitted a review, later dismissed
LGTM!

2024-11-28 11:05 UTC, PeterOu8 approved these changes
All g to go

2024-11-29 01:15 UTC, merged