add calendar
Ben0189/Blotz-Task-App pull request #147
Opened 2024-12-05 18:18 UTC by survivzhang

2024-12-06 12:32 UTC, Ben0189 requested changes

2024-12-06 12:32 UTC, Ben0189 commented on blotztask-ui/src/app/add-task/page.tsx
> +export function DatePickerWithRange({
can you move this into individual file?

create a folder call component if it does not exist yet
folder to create - blotztask-ui/src/app/add-task/component

then create a new file in the folder called calendar.tsx and put this code in there

2024-12-08 09:08 UTC, PeterOu8 commented
Could you please fix the build and test error [here](https://github.com/Ben0189/Blotz-Task-App/actions/runs/12185680925/job/33992471952?pr=147)

2024-12-08 21:44 UTC, closed without merging

2024-12-13 23:21 UTC, sol-wizard commented
closed pr, because work has been merged in a same branch {link}