finish the top row for all task page
Ben0189/Blotz-Task-App pull request #149
Opened 2024-12-07 11:30 UTC by JasonRenBang

![1733570825940](https://github.com/user-attachments/assets/2813a282-3e75-4e74-a721-c3dc97e2461e)
read to merge to main

2024-12-08 08:13 UTC, PeterOu8 requested changes
Please fix the error from this [link](https://github.com/Ben0189/Blotz-Task-App/actions/runs/12212513643). Make sure it passes all builds and tests. Other than that looks good to me.

2024-12-09 10:41 UTC, JasonRenBang commented
> Please fix the error from this [link](https://github.com/Ben0189/Blotz-Task-App/actions/runs/12212513643). Make sure it passes all builds and tests. Other than that looks good to me.

I have fixed the problem, please check it.

2024-12-09 14:26 UTC, PeterOu8 requested changes
Add in your changes and title and restore the deleted code otherwise other people's code may break

2024-12-09 14:26 UTC, PeterOu8 commented on blotztask-ui/src/app/task-list/page.tsx
> -    const loadTasks = async () => {
Why are you deleting these codes?

2024-12-10 01:59 UTC, JasonRenBang commented on blotztask-ui/src/app/task-list/page.tsx
> -    const loadTasks = async () => {
Those are the problem, cause they block build-and-test-frontend process. The responses said those variables and functions that never been used. I only have to delete them to make sure it can build and run frontend.

2024-12-10 02:15 UTC, PeterOu8 commented on blotztask-ui/src/app/task-list/page.tsx
> -    const loadTasks = async () => {
Yes, I understand but you need to keep the load tasks and task table intact you deleted.

2024-12-10 02:18 UTC, JasonRenBang commented on blotztask-ui/src/app/task-list/page.tsx
> -    const loadTasks = async () => {
but they still unused. that what the console responded to me

2024-12-10 02:19 UTC, JasonRenBang commented on blotztask-ui/src/app/task-list/page.tsx
> -    const loadTasks = async () => {
do you mean I should comment them instead of deleting?

2024-12-10 02:23 UTC, PeterOu8 commented on blotztask-ui/src/app/task-list/page.tsx
> -    const loadTasks = async () => {
The task list is used in TaskTable. and the loadTask function will always be called on first page render since it is in a useEffect hook.

2024-12-13 12:05 UTC, JasonRenBang commented on blotztask-ui/src/app/task-list/page.tsx
> -    const loadTasks = async () => {
yes I have make loadTask function back,

and 
![image](https://github.com/user-attachments/assets/f809d931-0eeb-4aeb-8684-2fb78462fcca)
there is nowhere to use taskList, which failed to build and test frontend, I have add console for the task.
console.log(taskList);

2024-12-13 12:06 UTC, JasonRenBang commented on blotztask-ui/src/app/task-list/page.tsx
> -    const loadTasks = async () => {
And please check other things are good and let me able to merge

2024-12-13 12:11 UTC, PeterOu8 requested changes

2024-12-13 12:11 UTC, PeterOu8 commented on blotztask-ui/src/app/task-list/page.tsx
> -    const loadTasks = async () => {
That is because you have deleted other lines of code asw. I am not trying to give you a hard time on teeny tiny thing but you can just run a git diff to see what you have missed.

2024-12-13 12:15 UTC, PeterOu8 commented on blotztask-ui/src/app/task-list/page.tsx
> -          <TaskTable tasks={taskList} />
Just add this line back and all other things are good to go

2024-12-13 12:26 UTC, JasonRenBang commented on blotztask-ui/src/app/task-list/page.tsx
> -          <TaskTable tasks={taskList} />
![1734092620686](https://github.com/user-attachments/assets/c17e0421-34ef-4be3-bb1a-31c61563929c)
I see the problem, it is for all tasks list, but my current task for this week is rewrite the all tasks list, and if you remember, you let me just delete it and addTask button.

2024-12-13 12:38 UTC, PeterOu8 approved these changes

2024-12-13 12:38 UTC, PeterOu8 commented on blotztask-ui/src/app/task-list/page.tsx
> -          <TaskTable tasks={taskList} />
I remember letting you delete the buttons but not the rest. Anyways. LGTM!

2024-12-13 12:44 UTC, merged