Get monthly stat endpoint
Ben0189/Blotz-Task-App pull request #150
Opened 2024-12-08 07:28 UTC by PeterOu8

All problems are fixed, and ready to merge.

2024-12-08 09:31 UTC, PeterOu8 commented
![image](https://github.com/user-attachments/assets/12bb473d-b056-4699-bf46-302b29cf7a41)

The return response follows the given format.

2024-12-11 23:54 UTC, sol-wizard requested changes

2024-12-11 23:54 UTC, sol-wizard commented on blotztask-api/Models/MonthlyStatDTO.cs
> +        public Tasks Data { get; set; }
```suggestion
        public Tasks Tasks { get; set; }
```

Data does not give any specific meaning to the object , ⬇️ readability

2024-12-11 23:54 UTC, sol-wizard commented on blotztask-api/Services/TaskService.cs
> +        var currentMonth = input.ToString("yyyy-MM");
i feel like this is unnecessary, let just make currentMonth as int in the DTO unless you have a good reason for it to be string

2024-12-13 07:50 UTC, PeterOu8 commented on blotztask-api/Services/TaskService.cs
> +        var currentMonth = input.ToString("yyyy-MM");
This is meant to be a format check as I don't want any wrong format of input to break the code.

2024-12-13 09:47 UTC, Ben0189 submitted a review, later dismissed

2024-12-13 10:01 UTC, sol-wizard approved these changes

2024-12-13 10:01 UTC, merged