All task page   UI changes   tasks list
Ben0189/Blotz-Task-App pull request #155
Opened 2024-12-15 12:49 UTC by JasonRenBang

I have done with it， please check.

2024-12-15 12:53 UTC, JasonRenBang commented
![1734266881691](https://github.com/user-attachments/assets/6740dab3-2156-41ee-bdc0-9f5c80afe5fb)
it looks like this.

2024-12-17 09:16 UTC, sol-wizard requested changes

2024-12-17 09:21 UTC, sol-wizard requested changes

2024-12-17 09:21 UTC, sol-wizard commented on blotztask-ui/src/app/task-list/components/task-table.tsx
> +export function TaskTable({ tasks }) {
```suggestion
export function TaskCard({ tasks }) {
```

if this is now custom card component , you can change the name

2024-12-19 12:20 UTC, JasonRenBang reviewed
I have done the changes.

2024-12-19 12:20 UTC, JasonRenBang reviewed
I have done the changes.

2024-12-19 12:33 UTC, JasonRenBang commented
![1734611615580](https://github.com/user-attachments/assets/62f49272-0006-43c8-b636-f1d5ac19187f)

2024-12-19 12:40 UTC, JasonRenBang commented on blotztask-ui/src/app/task-list/components/task-table.tsx
> +export function TaskTable({ tasks }) {
has changed the name

2024-12-19 12:42 UTC, JasonRenBang reviewed
done

2024-12-19 12:43 UTC, JasonRenBang reviewed
done

2024-12-19 12:47 UTC, PeterOu8 submitted a review, later dismissed
Just a suggestion in the comment. LGTM

2024-12-19 12:47 UTC, PeterOu8 commented on blotztask-ui/src/app/task-list/components/task-card.tsx
> +// interface TaskTableProps {
I personally will keep the DTO since we are using typeScript and it is ideal to have an interface to define the incoming data type.

2024-12-19 13:00 UTC, JasonRenBang commented on blotztask-ui/src/app/task-list/components/task-card.tsx
> +// interface TaskTableProps {
I perfer to use DTO, just at very begining, I found out the data I get is different from the the definition with DTO. In TaskItemDTO, it just three variables, but the data structure is a complex json structure where far more than three variables. I tried to use an interface class to inherit TaskItemDTO to fit these a lot variables. But later, I just found if I use “any” for tasks as the data type, it will less a lot coding, and more easier to read.

2024-12-19 13:37 UTC, sol-wizard approved these changes

2024-12-19 13:38 UTC, merged