Implement Get label by id endpoint
Ben0189/Blotz-Task-App pull request #93
Opened 2024-09-16 10:31 UTC by SuruiLiu

Endpoint can return correct data.
![488ad1da78f483f7509dab6d20551c8e](https://github.com/user-attachments/assets/9d937808-5095-4a0c-9b35-2e028f5d3275)

2024-09-17 03:58 UTC, sol-wizard requested changes

2024-09-17 03:58 UTC, sol-wizard commented on blotztask-api/BlotzTask.http
> +GET {{BlotzTask_HostAddress}}/api/label/1
what is this file for? do you need them?

2024-09-17 03:58 UTC, sol-wizard commented on blotztask-api/Controllers/LabelController.cs
> +            return Ok(await _labelService.GetLabelById(id)); // Return 200 OK with the label data
remove comment from gpt

2024-09-17 03:58 UTC, sol-wizard commented on blotztask-api/Controllers/LabelController.cs
> +    [Route("api/[controller]")]
can you put this in the last order?

`    [Authorize]
    [ApiController]
    [Route("api/[controller]")]`

2024-09-19 10:06 UTC, SuruiLiu commented on blotztask-api/BlotzTask.http
> +GET {{BlotzTask_HostAddress}}/api/label/1
This is a way to test the endpoint. Maybe we even don't need the file. 
![105ecba3b6e4eeda002a9f576a0306df](https://github.com/user-attachments/assets/c9c2952a-d7a2-4b20-9270-486b502c1055)

2024-09-20 11:38 UTC, sol-wizard approved these changes

2024-09-20 11:50 UTC, merged