Improve UI coming soon page fix
Ben0189/Blotz-Task-App pull request #96
Opened 2024-09-24 06:20 UTC by Wendiiiit

2024-09-27 12:36 UTC, sol-wizard requested changes

2024-09-27 12:36 UTC, sol-wizard commented on blotztask-ui/src/app/coming-soon/page.tsx
> +  },[]);
These effect does not looks like used any where in the code, please remove if it is not used

2024-09-27 12:36 UTC, sol-wizard commented on blotztask-ui/src/app/coming-soon/page.tsx
> +        <div className= "flex-1 mr-[50px]">
try to not use fix px

2024-09-27 12:36 UTC, sol-wizard commented on blotztask-ui/src/app/coming-soon/page.tsx
> +        <div className="text-left font-serif text-4xl italic text-white-800 animate-zoomOut">
We try to not having unnecessary animation in application if it does not gives value (animation is used mostly on website, gaming and etc)

2024-09-27 12:36 UTC, sol-wizard commented on blotztask-ui/src/app/coming-soon/page.tsx
> +      <div className= "fixed top-[350px] left-[95px]">
There are 2 problems here 

1. hardcoded value make css hard to maintain 
2. we try to avoid changing the position from static, this will made css very hard to maintain because element has been removed from the normal document flow 

Tips : try use flex box

2024-09-27 12:36 UTC, sol-wizard commented on blotztask-ui/src/app/coming-soon/page.tsx
> +         <div style={{ marginRight: '0px' }}>
no inline styling

2024-09-27 12:36 UTC, sol-wizard commented on blotztask-ui/src/app/coming-soon/page.tsx
> +          className="w-[640px] h-auto object-cover"
try to avoid fix px

2024-09-27 12:36 UTC, sol-wizard commented on blotztask-ui/public/comingsoon 2.webp
remove extra images

2024-09-28 03:47 UTC, Wendiiiit commented
Hi Ben, i have made changes based on your requests. Please review the code when its convenient.

2024-09-29 13:15 UTC, sol-wizard commented on blotztask-ui/public/comingsoon 2.webp
@Wendiiiit dont resolve comment without reply, you will missed some comment if you do this , for example you missed to fix this comment

2024-10-04 06:30 UTC, Wendiiiit commented on blotztask-ui/public/comingsoon 2.webp
Hi Ben, i resolved the comment because i did remove the extra image, is it not showing from your side?

2024-10-04 06:55 UTC, Wendiiiit commented on blotztask-ui/public/comingsoon 2.webp
![image](https://github.com/user-attachments/assets/b78a3459-1569-447f-b78f-f81432051d54)

2024-10-04 06:55 UTC, Wendiiiit commented on blotztask-ui/public/comingsoon 2.webp
![image](https://github.com/user-attachments/assets/141c5fbb-be7d-4168-ba39-c0d4cd35f565)

2024-10-05 05:50 UTC, sol-wizard approved these changes

2024-10-05 07:39 UTC, merged