add dynamic navbar dependding on user login session
Ben0189/Blotz-Task-App pull request #97
Opened 2024-09-27 13:30 UTC by nets7snipper

1. Dynamic nav bar show different layout depending on user session
2. Change sign in entrance
3. Change css to make the look good
![image](https://github.com/user-attachments/assets/cd3e8c07-daa6-4c51-afaf-3b6d5f5a0f47)
![image](https://github.com/user-attachments/assets/fce3ea23-c0a7-45b8-84c0-6ce03b5660d5)
![image](https://github.com/user-attachments/assets/4a042aa5-6513-4fe1-b7b4-1d694d476419)
![image](https://github.com/user-attachments/assets/0e15ae97-a05f-4912-8eb8-5077756e2f55)

2024-09-27 13:40 UTC, nets7snipper commented
![image](https://github.com/user-attachments/assets/a8ade7e4-5d0b-438c-999d-ce44787496ac)

2024-09-27 14:06 UTC, Ben0189 requested changes

2024-09-27 14:06 UTC, Ben0189 commented on blotztask-ui/src/app/signin/page.jsx
> +      window.location.href = '/'; // 登录后重定向到主页
In Next.js, using window.location for navigation is not recommended because it triggers a full page reload, which defeats the purpose of using a React framework like Next.js that provides client-side navigation.

Instead, you should use Next.js's built-in useRouter hook or the Link component, which allow client-side navigation without reloading the page. This improves performance and provides a smoother user experience. 

```
const router = useRouter();
  
  const handleNavigation = () => {
    router.push('/new-page');  
  };

```

2024-09-27 14:06 UTC, Ben0189 commented on blotztask-ui/src/app/signin/page.jsx
> +        <h1 className={styles.title}>用户登录</h1>
change to english

2024-09-27 14:06 UTC, Ben0189 commented on blotztask-ui/src/middleware.ts
is there a reason for removing middleware file?

2024-09-27 14:06 UTC, Ben0189 commented on blotztask-ui/src/fdsfds.ts
> +export { default } from "next-auth/middleware";
what is this folder

2024-09-27 14:06 UTC, Ben0189 commented on blotztask-ui/src/styles/globals.css
> +.main:before {
why we need this ? main things here is always avoid to use position absolute in css 
https://stackoverflow.com/questions/186044/is-it-considered-bad-practice-to-use-absolute-positioning

Reason:  hard to maintain

2024-09-27 14:06 UTC, Ben0189 commented on blotztask-ui/src/styles/globals.css
> +.main:after {
same here

2024-09-27 14:06 UTC, Ben0189 commented on blotztask-ui/src/styles/globals.css
> +  position: absolute;
absolute

2024-09-28 13:47 UTC, nets7snipper commented on blotztask-ui/src/app/navbar/main-nav.tsx
> +            <div className='sm:flex hidden'>
yes, it would be hidden if the screen is shrinked, and a nav for mobile shoud be added for the small screen
![image](https://github.com/user-attachments/assets/3c75225f-133e-482a-84a7-089228352486)
![image](https://github.com/user-attachments/assets/62470a2c-7eba-45d0-8b03-2992ef64caab)

2024-09-28 13:47 UTC, nets7snipper commented on blotztask-ui/src/app/signin/LoginPage.module.css
> +    margin: 0;
No just copy from other apps,, hhh

2024-09-28 13:48 UTC, nets7snipper commented on blotztask-ui/src/app/signin/LoginPage.module.css
> +  .container {
maybe never used, I will remove it

2024-09-28 13:49 UTC, nets7snipper commented on blotztask-ui/src/app/signin/LoginPage.module.css
> +  .formContainer {
fine, I would told it to gpt, hhh, he generated it for me

2024-09-28 13:53 UTC, nets7snipper commented on blotztask-ui/src/middleware.ts
I just don't want to no-login guests being redirect to the sigin page. Can we just let them see the homepage and some other page to attract them to sign up?

2024-09-28 13:54 UTC, nets7snipper commented on blotztask-ui/src/styles/globals.css
> +.main:before {
cool, just copied it from other sample repo. I have little knowledge about css, so just use others template for the page effect.

2024-09-28 18:05 UTC, nets7snipper commented on blotztask-ui/.env.production
> -NEXT_PUBLIC_API_BASE_URL_WITH_API=https://wapp-blotztaskapp.azurewebsites.net/api
fixed

2024-10-05 08:22 UTC, sol-wizard approved these changes

2024-10-05 08:23 UTC, Ben0189 approved these changes

2024-10-05 23:01 UTC, cloverluo112 approved these changes

2024-10-05 23:01 UTC, merged